# Generated by Django 3.2.7 on 2021-11-01 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='', upload_to='./photos')),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
